#!/usr/bin/env bash
# Check if the file ~/.tmux.conf exists and delete it if it does
if [ -f "$HOME/.tmux.conf" ]; then
  rm "$HOME/.tmux.conf"
fi
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -s $(pwd)/.tmux.conf ~/.tmux.conf

b